spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweater2
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  freemarker:
    expose-request-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    check-template-location: true

  mail:
    host: smtp.yandex.ru
    username: vernik3@tut.by
    password: glmmrwgqiyvzfhkg       # Тот самый 16-значный пароль приложения
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true             # Для порта 465 SSL должен быть включен
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  flyway:
    out-of-order: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

# Кастомные настройки
upload:
  path: /home/viarzilinm/Бенч проекты/testdir2

recaptcha:
  secret: 6LcezZ0UAAAAAB57r6UNXDWm-_flqlUEhetBQdAa

mail:
  debug: true

logging:
  file:
    name: /home/viarzilinm/Бенч проекты/app.log
  level:
    org.hibernate.SQL: INFO
    org.flywaydb: DEBUG
